<?php

function change_contact_form_alter(&$form, &$form_state, $form_id) {
// print_r($form_id);
    if($form_id == 'contact_site_form') {
        // print '<pre>';
        // print_r($form);
        // print '</pre>';
    $form['copy']['#access'] = 0;
    $form['subject']['#title'] = 0;
    $form['subject']['#type'] = 0;
    $form['name']['#required'] = 0;
    $form['name']['#default_value'] = '';
    $form['mail']['#required'] = 0;
    $form['mail']['#default_value'] = '';
    $form['message']['#required'] = 0;
      }
}
